name: Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:

      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y -o Acquire::Retries=50 \
            python3 \
            python3-pycryptodome \
            xxd \
            binutils \
            build-essential \
            g++ \
            gcc \
            gcc-aarch64-linux-gnu \
            gcc-x86-64-linux-gnu \
            git-core \
            iasl \
            make \
            perl \
            python-is-python3 \
            liblzma-dev \
            lzma-dev \
            uuid-dev \
            zip \
            wget
          sudo wget https://ftp.gnu.org/gnu/mtools/mtools_4.0.38_amd64.deb
          sudo dpkg -i mtools_4.0.38_amd64.deb
          sudo ln -sf /bin/bash /bin/sh 

      - name: Build everything
        run: |
          mkdir -p keys
          echo "${{ secrets.SIGNING_KEY }}" > keys/private.pem
          make -j8 IMAGE_NAME=ubuntu-jammy
          make -j8 IMAGE_NAME=k3s-jammy

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}

      - name: Upload (flash-eeprom-ubuntu-jammy.img.xz)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_name: flash-eeprom-ubuntu-jammy.img.xz
          asset_path: dist/flash-eeprom-ubuntu-jammy.img.xz
          asset_content_type: application/octet-stream

      - name: Upload (boot-ubuntu-jammy.img)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_name: boot-ubuntu-jammy.img
          asset_path: dist/boot-ubuntu-jammy.img
          asset_content_type: application/octet-stream

      - name: Upload (boot-ubuntu-jammy.sig)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_name: boot-ubuntu-jammy.sig
          asset_path: dist/boot-ubuntu-jammy.sig
          asset_content_type: application/octet-stream

      - name: Upload (ubuntu-jammy.ipxe)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_name: ubuntu-jammy.ipxe
          asset_path: chained/ubuntu-jammy.ipxe
          asset_content_type: text/plain

      - name: Upload (flash-eeprom-k3s-jammy.img.xz)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_name: flash-eeprom-k3s-jammy.img.xz
          asset_path: dist/flash-eeprom-k3s-jammy.img.xz
          asset_content_type: application/octet-stream

      - name: Upload (boot-k3s-jammy.img)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_name: boot-k3s-jammy.img
          asset_path: dist/boot-k3s-jammy.img
          asset_content_type: application/octet-stream

      - name: Upload (boot-k3s-jammy.sig)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_name: boot-k3s-jammy.sig
          asset_path: dist/boot-k3s-jammy.sig
          asset_content_type: application/octet-stream

      - name: Upload (k3s-jammy.ipxe)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_name: k3s-jammy.ipxe
          asset_path: chained/k3s-jammy.ipxe
          asset_content_type: text/plain
